### PR TITLE
Separate public front-end.

### LINKED ISSUE #51: Separate Public-Frontend

### PR DESCRIPTION
**Pull request by basilv**
Fixes #51

### CODE REVIEW

**Review by DerekRoberts — DISMISSED** [review]
Good job!  :)

**Review by DerekRoberts — APPROVED** [review]

**Comment by ianliuwk1019** [comment]
This is for reference:

During troubleshooting and many experiments when looking into Typescript tscnofig documentation, this is what leads me to fix the issues of public frontend using common libs (not within monorepo and not under root directory of /public):

- Previously under monorepo, for public frontend to reference to common libs, it was to use tsconfig.json 'path'configuration like so:

`
		"paths": {
		  "@public-core/*": ["core/*"],
		  "@api-client": ["../../libs/client/typescript-ng"],
		  "@utility/*": ["../../libs/utility/src/*"],
		}
`
this works easily under monorepo and no other setup required (If I am correct).
		
- After new /public separation and trying to keep everything still the same except some required folder path adjustment at the import of classes and configurations, public build became failing. And the tsconfig.json 'paht' reference to common libs (even when the path is correct) didn't work either.
-- Lots of errors during build. Hard to understand those errors as well.
-- Those errors prompted me to search if anything wrong or additional settings required in tsconfig.json.

		
- After many attempts to adjust tsconfig.json, including to use 'include', 'rootDirs', 'project references' etc, although some of the tweaks can make import error (at vscode editor) goes away, during build, it was still failing for not able to find modules from commoin libs.

		
- One of the interesting and specific error was the build was complaining for not being able to use Leaflet correctly despite I didn't even change the Leaflet dependency version at parent package.json and at '/public' folder package.json.
-- Nothing is changed for Leaflet but why was it failing when building '/public' from '/public' context?
-- Two things made me work toward the right direction:
		=> 
--- Basil's keen eyes that he was able to point out although nothing changes in package.json, the version of Leaflet did get changed in package-lock.json and made it incompitable with the existing code.
--- The fact that in the pipeline, if we install parent's package.json dependencies at the parent context level first and then install/build the new '/public', the public frontnend will work (nothing change in package.json for leaflet version on both).
--- Although I could not explain why (in my mind I thought every dependencies has already been resolved and thus '/public/node_modules' was created for the purpose) with the sibling common libs folder it needs parent's package.json installed in order to build '/public'. Why could node/npm not just see two projects 'include'ed or 'rootDirs'ed or 'references'ed (based on tsconfig.json) to build under one '/public/package.json'? 
But it was enough for me to feel and assume internally nodejs does its finding of dependencies separately when they are not under the same root folder (package.json).

					 
- I began again with creating a totally new folder to host just the '/public' and '/libs' sibling to each other then:
-- add a new package.json to '/libs' and tsconfig.json (probably not necessary) just enough dependencies configured for '/libs' purpose.
`
			{
			  "name": "@fom/shared",
			  "description": "FOM Shared Library",
			  "version": "0.0.1",
			  "main": "dist/index.js",
			  "types": "dist/index.d.ts",
			  "dependencies": {
				"@angular/common": "^11.2.14",
				"@angular/compiler": "^11.2.14",
				"@angular/core": "^11.2.14",
				"leaflet": "~1.7.1",
				"leaflet.markercluster": "~1.5.3",
				"linkify-it": "^3.0.3",
				"rxjs": "~7.5.5",
				"tslib": "^2.3.1",
				"zone.js": "^0.11.4"
			  },
			  "devDependencies": {
				"@types/leaflet": "~1.7.11",
				"@types/leaflet.markercluster": "~1.5.1",
				"typescript": "~4.1.6"
			  }
			}
`
-- change back and still keep the '/public' tsconfig 'path' settings to reference to sibling 'libs' as is
`
			"paths": {
			  "@public-core/*": ["core/*"],
			  "@api-client": ["../../libs/client/typescript-ng"],
			  "@utility/*": ["../../libs/utility/src/*"],
			}
`
-- remove parent package.json, tsconfig.json and everything unnecessary.
-- do a 'npm install' on '/libs' first.
-- then as usual, switch to '/public' to do 'npm run build:public' and then serve it with 'npm run start:public'.
* ==> It worked!
		
- From then, it was smooth to migrate my working sample to the public-separation branch.


@franTarkenton

**Comment by basilv** [comment]
The other alternative solution would be to build the public libs as an npm package and then express a dependency on it from public component. In terms of complexity, this essentially adds an extra step (e.g. to the Dockerfile build process) and doesn't really gain much, so we chose to leave it as is. Common libs is essentially included into Public, so public build process includes the libs, but for this to work common libs needs its own dependencies (separate package.json with dependencies installed separately).

**Comment by DerekRoberts** [comment]
@basilv I like the current solution.  Publishing libs through government would require setup and getting approvals.  Yuck.

**Pull request merged**
