### PR TITLE
hotfix: #696 oc namespace config

### LINKED ISSUE #696: Fix deployment script for environment OC_NAMESAPCE
**Describe the Bug**
FOM production has a failure on Sept 13 for two batch jobs (workflow change/forest client refresh) and that caused business to report some FOM (ID: 1827) the status did not get changed to commenting open in the morning (batch job run) and still remained in PUBLISHED.

After team troubleshooting together, the discovery was both production and test environments all are pulling image from "-dev" space (from OC_NAMESPACE config).

The root cause was the recent PR change for the openshift deployment yml script to referencing the `OC_NAMESPACE` from Github environment/secret instead of previous hardcoded namespace value. This change did not work for TEST and PROD.
From the Github action environment/secret that there was still a **default** repository (${OC_NAMESPACE}) value and during deployment it seems the deployment(test/prod) all gets the (OC_NAMESPACE) value from the default repository value, although there were OC_NAMESPACE configured value setup in Github for other environments (-test/-prod).

**Expected Behaviour**
`${OC_NAMESPACE}` should referencing the correct value from environment specific.

**Actual Behaviour**
It was always the "dev" (the default one at the repository secret).

**Action to take**
- Either revert back to previous configuration for using direct hardcode name space for each environment deployment at configuration, or get rid of Github repository (default) OC_NAMESPACE variable and add `environment` for -dev environment at openshift yaml to referencing the correct value from Github for all environments (dev/test/prod).

**Additional context**

### PR DESCRIPTION
**Pull request by craigyu**
Update the pr-open.yml to have a specific environment defined

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
 - [api](https://fom-47.apps.silver.devops.gov.bc.ca/api)
 - [admin](https://fom-47.apps.silver.devops.gov.bc.ca/admin)
 - [public](https://fom-47.apps.silver.devops.gov.bc.ca/public)

Once merged, code will be promoted and handed off to following workflow run.
 - [Main Merge Workflow](https://github.com/bcgov/nr-fom/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by basilv — COMMENTED** [review]
I assume this works because you are removing the OC_NAMESPACE repository variable and just leaving it as an environment variable, including for a new dev environment?

**Comment by craigyu** [comment]
> I assume this works because you are removing the OC_NAMESPACE repository variable and just leaving it as an environment variable, including for a new dev environment?

That's exactly it

**Comment by DerekRoberts** [comment]
@craigyu We probably don't need this PR anymore.  I just removed the var completely!  https://github.com/bcgov/nr-fom/pull/701

**Comment by craigyu** [comment]
> @craigyu We probably don't need this PR anymore. I just removed the var completely! #701

Looks like magic and a better solution to me

**Comment by craigyu** [comment]
done in #701

**Pull request closed without merging**
