### PR TITLE
fix(deps): update dependency @nestjs/cli to ~10.1.0

### PR DESCRIPTION
**Pull request by bcgov-devops**
This PR contains the following updates:

| Package | Type | Update | Change | Pending |
|---|---|---|---|---|
| [@nestjs/cli](https://togithub.com/nestjs/nest-cli) | dependencies | minor | [`~10.0.0` -> `~10.1.0`](https://renovatebot.com/diffs/npm/@nestjs%2fcli/10.0.5/10.1.10) | `10.1.11` |

---

### Release Notes

<details>
<summary>nestjs/nest-cli</summary>

### [`v10.1.10`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.10)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.9...10.1.10)

-   Merge pull request [#&#8203;2188](https://togithub.com/nestjs/nest-cli/issues/2188) from JohanManders/swc-reload ([`99d32e7`](https://togithub.com/nestjs/nest-cli/commit/99d32e7f))
-   chore(deps): update commitlint monorepo to v17.6.7 ([`e8b82b9`](https://togithub.com/nestjs/nest-cli/commit/e8b82b92))
-   fix(swc): SWC doesn't reload the application on Windows ([`ad30bcb`](https://togithub.com/nestjs/nest-cli/commit/ad30bcbe))
-   chore(deps): update dependency [@&#8203;swc/core](https://togithub.com/swc/core) to v1.3.70 ([`cb547fa`](https://togithub.com/nestjs/nest-cli/commit/cb547fad))
-   chore(deps): update typescript-eslint monorepo to v6.1.0 ([`e8d82e5`](https://togithub.com/nestjs/nest-cli/commit/e8d82e54))

### [`v10.1.9`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.9)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.8...10.1.9)

-   Merge pull request [#&#8203;2159](https://togithub.com/nestjs/nest-cli/issues/2159) from nestjs/renovate/angular-cli-monorepo ([`707cb55`](https://togithub.com/nestjs/nest-cli/commit/707cb551))
-   Merge pull request [#&#8203;2169](https://togithub.com/nestjs/nest-cli/issues/2169) from nestjs/renovate/tsconfig-paths-webpack-plugin-4.x ([`56c7b83`](https://togithub.com/nestjs/nest-cli/commit/56c7b839))
-   Merge pull request [#&#8203;2179](https://togithub.com/nestjs/nest-cli/issues/2179) from micalevisk/perf/eage-load-compilers ([`7609844`](https://togithub.com/nestjs/nest-cli/commit/76098446))
-   Merge pull request [#&#8203;2175](https://togithub.com/nestjs/nest-cli/issues/2175) from sezanzeb/patch-1 ([`36a7111`](https://togithub.com/nestjs/nest-cli/commit/36a7111d))
-   chore: ignore type declaration files from eslint checking ([`5cc0c8a`](https://togithub.com/nestjs/nest-cli/commit/5cc0c8ad))
-   perf(actions): on build, only import the used compiler ([`984b697`](https://togithub.com/nestjs/nest-cli/commit/984b697c))
-   chore(deps): update dependency release-it to v16.1.2 ([`27faa64`](https://togithub.com/nestjs/nest-cli/commit/27faa647))
-   chore(deps): update dependency eslint to v8.45.0 ([`d368823`](https://togithub.com/nestjs/nest-cli/commit/d3688239))
-   fix(cli): don't fail if the argument contains multiple '--' ([`72f94f1`](https://togithub.com/nestjs/nest-cli/commit/72f94f1e))
-   chore(deps): update dependency [@&#8203;swc/core](https://togithub.com/swc/core) to v1.3.69 ([`e21dd65`](https://togithub.com/nestjs/nest-cli/commit/e21dd65a))
-   fix(deps): update dependency tsconfig-paths-webpack-plugin to v4.1.0 ([`4dd8bf2`](https://togithub.com/nestjs/nest-cli/commit/4dd8bf23))
-   fix(deps): update angular-cli monorepo to v16.1.4 ([`e8dd638`](https://togithub.com/nestjs/nest-cli/commit/e8dd6388))

### [`v10.1.8`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.8)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.7...10.1.8)

-   Merge pull request [#&#8203;2161](https://togithub.com/nestjs/nest-cli/issues/2161) from powerfulyang/master ([`c2e2d26`](https://togithub.com/nestjs/nest-cli/commit/c2e2d263))
-   Merge pull request [#&#8203;2155](https://togithub.com/nestjs/nest-cli/issues/2155) from tuxmachine/patch-1 ([`be5d1d0`](https://togithub.com/nestjs/nest-cli/commit/be5d1d0e))
-   chore(deps): update typescript-eslint monorepo to v6 ([`2d8a8d5`](https://togithub.com/nestjs/nest-cli/commit/2d8a8d51))
-   chore(deps): update typescript-eslint monorepo to v5.62.0 ([`e13f4df`](https://togithub.com/nestjs/nest-cli/commit/e13f4df4))
-   chore(deps): update dependency [@&#8203;types/jest](https://togithub.com/types/jest) to v29.5.3 ([`8d512ee`](https://togithub.com/nestjs/nest-cli/commit/8d512ee3))
-   chore(deps): update dependency release-it to v16.1.0 ([`ac30e00`](https://togithub.com/nestjs/nest-cli/commit/ac30e008))
-   fix(swc): deepMerge didn't handle array type properly ([`bc18e83`](https://togithub.com/nestjs/nest-cli/commit/bc18e831))
-   chore(deps): update dependency jest to v29.6.1 ([`1b9ab26`](https://togithub.com/nestjs/nest-cli/commit/1b9ab264))
-   chore(deps): update dependency release-it to v16 ([`77915d8`](https://togithub.com/nestjs/nest-cli/commit/77915d8d))
-   chore(deps): update dependency prettier to v3 ([`ac0a98d`](https://togithub.com/nestjs/nest-cli/commit/ac0a98dc))
-   fix(swc): don't set missing class fields ([`37813f4`](https://togithub.com/nestjs/nest-cli/commit/37813f46))

### [`v10.1.7`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.7)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.6...10.1.7)

-   feat(plugin): use local ts binary for meta printer ([`1fc18f6`](https://togithub.com/nestjs/nest-cli/commit/1fc18f61))

### [`v10.1.6`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.6)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.5...10.1.6)

-   fix(plugin): use unknown to fix ts incompatibility issues ([`882722d`](https://togithub.com/nestjs/nest-cli/commit/882722d3))

### [`v10.1.5`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.5)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.4...10.1.5)

-   Merge branch 'master' of https://github.com/nestjs/nest-cli ([`f9ecab8`](https://togithub.com/nestjs/nest-cli/commit/f9ecab86))
-   fix(visitors): fallback type args to any ([`c3149ba`](https://togithub.com/nestjs/nest-cli/commit/c3149bac))
-   chore(deps): update dependency [@&#8203;swc/core](https://togithub.com/swc/core) to v1.3.68 ([`879cd5d`](https://togithub.com/nestjs/nest-cli/commit/879cd5d7))
-   chore(deps): update dependency jest to v29.6.0 ([`c7e0640`](https://togithub.com/nestjs/nest-cli/commit/c7e0640f))

### [`v10.1.4`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.4)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.3...10.1.4)

-   refactor: update readonly visitor methods to take type args ([`d0f086d`](https://togithub.com/nestjs/nest-cli/commit/d0f086d7))

### [`v10.1.3`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.3)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.2...10.1.3)

-   fix: swc default factory should be usable for swc loader ([`b00c3e1`](https://togithub.com/nestjs/nest-cli/commit/b00c3e1c))

### [`v10.1.2`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.2)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.1...10.1.2)

-   Merge branch 'master' of https://github.com/nestjs/nest-cli ([`c662ef7`](https://togithub.com/nestjs/nest-cli/commit/c662ef77))
-   fix(swc): fix file watching (out dir path resolution) ([`2d0c6fd`](https://togithub.com/nestjs/nest-cli/commit/2d0c6fd3))
-   chore(deps): update typescript-eslint monorepo to v5.61.0 ([`b63fa4c`](https://togithub.com/nestjs/nest-cli/commit/b63fa4c1))

### [`v10.1.1`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.1)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.1.0...10.1.1)

-   Merge branch 'master' of https://github.com/nestjs/nest-cli ([`e2e52dc`](https://togithub.com/nestjs/nest-cli/commit/e2e52dcb))
-   fix: retrieve builder opts by builder context ([`be12359`](https://togithub.com/nestjs/nest-cli/commit/be123593))
-   chore(deps): update dependency eslint to v8.44.0 ([`c32a30a`](https://togithub.com/nestjs/nest-cli/commit/c32a30ab))
-   chore(deps): update dependency [@&#8203;types/node](https://togithub.com/types/node) to v18.16.19 ([`85826de`](https://togithub.com/nestjs/nest-cli/commit/85826de0))
-   chore: remove deprecated tag ([`ee4427d`](https://togithub.com/nestjs/nest-cli/commit/ee4427d7))

### [`v10.1.0`](https://togithub.com/nestjs/nest-cli/releases/tag/10.1.0)

[Compare Source](https://togithub.com/nestjs/nest-cli/compare/10.0.5...10.1.0)

-   Merge pull request [#&#8203;2144](https://togithub.com/nestjs/nest-cli/issues/2144) from nestjs/renovate/ts-loader-9.x ([`65396dc`](https://togithub.com/nestjs/nest-cli/commit/65396dcd))
-   chore(deps): update dependency ts-loader to v9.4.4 ([`3c82cde`](https://togithub.com/nestjs/nest-cli/commit/3c82cde6))
-   Merge pull request [#&#8203;2145](https://togithub.com/nestjs/nest-cli/issues/2145) from nestjs/renovate/angular-cli-monorepo ([`c6fb08c`](https://togithub.com/nestjs/nest-cli/commit/c6fb08c2))
-   Merge pull request [#&#8203;2132](https://togithub.com/nestjs/nest-cli/issues/2132) from nestjs/renovate/webpack-5.x ([`b5135a8`](https://togithub.com/nestjs/nest-cli/commit/b5135a8e))
-   Merge pull request [#&#8203;2148](https://togithub.com/nestjs/nest-cli/issues/2148) from nestjs/renovate/ts-jest-29.x ([`1c470aa`](https://togithub.com/nestjs/nest-cli/commit/1c470aa6))
-   Merge pull request [#&#8203;2147](https://togithub.com/nestjs/nest-cli/issues/2147) from nestjs/renovate/swc-monorepo ([`e8a2299`](https://togithub.com/nestjs/nest-cli/commit/e8a22997))
-   fix(deps): update dependency webpack to v5.88.1 ([`6154ffa`](https://togithub.com/nestjs/nest-cli/commit/6154ffa5))
-   fix(deps): update angular-cli monorepo to v16.1.3 ([`4e8a995`](https://togithub.com/nestjs/nest-cli/commit/4e8a995d))
-   chore(deps): update dependency ts-jest to v29.1.1 ([`5835ad5`](https://togithub.com/nestjs/nest-cli/commit/5835ad5f))
-   chore(deps): update dependency [@&#8203;swc/core](https://togithub.com/swc/core) to v1.3.67 ([`3acbc45`](https://togithub.com/nestjs/nest-cli/commit/3acbc45f))
-   Merge branch 'master' of https://github.com/nestjs/nest-cli ([`a56e3f3`](https://togithub.com/nestjs/nest-cli/commit/a56e3f33))
-   test: update nest configuration loader tests ([`989a9f8`](https://togithub.com/nestjs/nest-cli/commit/989a9f8a))
-   Merge pull request [#&#8203;2146](https://togithub.com/nestjs/nest-cli/issues/2146) from nestjs/renovate/typescript-5.x ([`594c041`](https://togithub.com/nestjs/nest-cli/commit/594c0417))
-   Merge branch 'master' of https://github.com/nestjs/nest-cli ([`b8a008f`](https://togithub.com/nestjs/nest-cli/commit/b8a008fe))
-   Merge branch 'medz-swc-io' ([`72599a0`](https://togithub.com/nestjs/nest-cli/commit/72599a0d))
-   test: skip flaky test ([`f6264ab`](https://togithub.com/nestjs/nest-cli/commit/f6264abe))
-   feat: introduce builder options ([`a231941`](https://togithub.com/nestjs/nest-cli/commit/a2319410))
-   fix(deps): update dependency typescript to v5.1.6 ([`bba1342`](https://togithub.com/nestjs/nest-cli/commit/bba1342b))
-   Merge pull request [#&#8203;2142](https://togithub.com/nestjs/nest-cli/issues/2142) from nestjs/renovate/typescript-5.x ([`7252787`](https://togithub.com/nestjs/nest-cli/commit/72527870))
-   Merge pull request [#&#8203;2133](https://togithub.com/nestjs/nest-cli/issues/2133) from nestjs/renovate/angular-cli-monorepo ([`aa488e2`](https://togithub.com/nestjs/nest-cli/commit/aa488e23))
-   Merge pull request [#&#8203;2143](https://togithub.com/nestjs/nest-cli/issues/2143) from nestjs/renovate/lint-staged-13.x ([`05b01b4`](https://togithub.com/nestjs/nest-cli/commit/05b01b48))
-   chore(deps): update dependency lint-staged to v13.2.3 ([`e4e1229`](https://togithub.com/nestjs/nest-cli/commit/e4e1229b))
-   fix(deps): update dependency typescript to v5.1.5 ([`2c2317f`](https://togithub.com/nestjs/nest-cli/commit/2c2317f3))
-   style(swc): Change the OR logical operation to a null operation ([`ede05a6`](https://togithub.com/nestjs/nest-cli/commit/ede05a6d))
-   style(swc): Remove extra blank lines ([`5723119`](https://togithub.com/nestjs/nest-cli/commit/57231197))
-   chore(swc): Easier to maintain SWC cli option defaults using struct ([`c70aa59`](https://togithub.com/nestjs/nest-cli/commit/c70aa598))
-   feat(swc): Config SWC cli in nest-cli.json ([`3b1c1c4`](https://togithub.com/nestjs/nest-cli/commit/3b1c1c4c))
-   fix(swc): SWC does not support custom `sourceRoot` and custom output ([`fde03fa`](https://togithub.com/nestjs/nest-cli/commit/fde03fae))
-   chore(deps): update typescript-eslint monorepo to v5.60.1 ([`90387b2`](https://togithub.com/nestjs/nest-cli/commit/90387b2d))
-   fix(deps): update angular-cli monorepo to v16.1.1 ([`c632260`](https://togithub.com/nestjs/nest-cli/commit/c6322605))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Review by DerekRoberts — COMMENTED** [review]
Should be safe.

**Comment by ianliuwk1019** [comment]
Business enhancement tickets on going.
No renovate pr merging at this time before business enhancement tickets are delivered to business owner.
(Except if PO agrees and risk discussed)
@gormless87

**Comment by DerekRoberts** [comment]
> Business enhancement tickets on going. No renovate pr merging at this time before business enhancement tickets are delivered to business owner. (Except if PO agrees and risk discussed) @gormless87

If that goes on for long it will create security issues and more work down the road.  You officially have my objection, but there won't be further interference.

@ianliuwk1019 @basilv @MCatherine1994 @gormless87  @webgismd

**Comment by ianliuwk1019** [comment]
This is a partial update for NestJS. Typically I am not sure and don't feel this Renovate bot update package partially for the entire framework strategy is good.

With this update, our current api will sit on NestJS with (**"@nestjs/cli": "~10.1.0"** and **"@nestjs/typeorm": "^10.0.0"**), while other packages in the NestJS framework are at **v9** not 10. 
image
Not sure if in the future if this continues, would it be too much inconsistencies with both versions (v9 and v10) for NestJS and NestJS backend start to fail apart. (Note, "@nestjs/typeorm": "^10.0.0" was also from Renovate bot update)

Hi @basilv , do you feel we should plan for NestJs v10 upgrade sometime later (don't know when, probably depends), or ignore this one for now (although @nestjs/typeorm at v10 is working currently)?

**Comment by DerekRoberts** [comment]
@basilv @ianliuwk1019 He's right.  Renovate has no intelligence when it comes to grouping.  We can set up rules, but that would mostly be to help others going forward.  I think this PR should be closed in favour of a NestJs v10 upgrade issue.

**Comment by ianliuwk1019** [comment]
Discussed in scrum, will close this partial one in favor of next NestJs framework upgrade (will plan).

**Pull request closed without merging**
